Numpy Basic to Adcance

Basics

Numpy importing

In [2]:
import numpy as np

# Creating Numpy Array

1D array

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


2D array

In [4]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


creating array in range

In [5]:
range=np.arange(0,10,2) # start stop step
print(range)

[0 2 4 6 8]


creating array in no.of.values between start and end divide equaly

In [6]:
lin=np.linspace(1,5,10) # start end no.of.values
print(lin)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Creating logarithmic scale array

In [7]:
log=np.logspace(1,3,3) # start with 10^1 to 10^3
print(log)

[  10.  100. 1000.]


Creating a Empty array

In [8]:
emp=np.empty([2,4])
print(emp)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.04721870e-306]
 [1.69119330e-306 1.42413555e-306 1.78019082e-306 1.37959740e-306]]


get dimension

In [9]:
a.ndim

1

In [10]:
b.ndim

2

get shape

In [11]:
a.shape

(3,)

In [12]:
b.shape

(2, 3)

get type

In [13]:
a.dtype

dtype('int64')

In [14]:
b.dtype

dtype('int64')

specify the type

In [15]:
b=np.array([[1,2,3],[1,2,3]],dtype='int16')
b.dtype

dtype('int16')

get size as (bytes)

In [16]:
a.itemsize

8

In [17]:
b.itemsize

2

get total no of element in array

In [18]:
a.size

3

In [19]:
b.size

6

Get total size is stored

In [20]:
a.size*a.itemsize

24

In [21]:
# alternative way 
a.nbytes

24

In [22]:
b.nbytes

12

# Accessing/changigng specific elements,row,columns

In [23]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


Accessing a specific element

In [24]:
# array_name[row,colum]
a[1,5]

np.int64(13)

In [25]:
#negative index is also poosible
a[1,-2]

np.int64(13)

Accessing specific row

In [26]:
# array_name[row, slicing operation]
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

Accessing specific columns

In [27]:
# array_name[ slicing operation : column]
a[:,2]

array([ 3, 10])

Slicing operation in the Array

In [28]:
# array_name[row, slicing operation]
a[0, 1:6:2]

array([2, 4, 6])

indexing by list 

In [29]:
c=np.array([1,2,3,4,5,5,7,8,9])
c[[0,2,8]]

array([1, 3, 9])

Changing the element

In [30]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


changing the row

In [31]:
a[0,2:4]=5
print(a)

[[ 1  2  5  5  5  6  7]
 [ 8  9 10 11 12 20 14]]


changing the column

In [32]:
a[:,2]=[0,0]
print(a)

[[ 1  2  0  5  5  6  7]
 [ 8  9  0 11 12 20 14]]


3D array Creating

In [33]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Accessing element in 3D

In [34]:
b[:,:,:]  # all the element  in array
b[0,1,:]  # first row in that second row in that all element
b[0,:,:]  # first row all element

array([[1, 2],
       [3, 4]])

Changing the element /row /columns

In [35]:
b[0,0,1]=5
print(b)

[[[1 5]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
b[1,:,0]=0
print(b)
#b[0,1,:]=[9,9,9] # error

[[[1 5]
  [3 4]]

 [[0 6]
  [0 8]]]


Fancy indexing

In [37]:
arr=np.array([1,2,3,4,5,6])# value
ind=[1,3,5] #index 
arr[ind]

array([2, 4, 6])

Take key using accessing the element

In [38]:
arr=np.array([1,2,3,4,5,6])# value
ind=[1,3,5] #index 
np.take(arr,ind)

array([2, 4, 6])

accessing element like loop

In [39]:
arr=np.array([[1,2,3],[4,5,6]])# value
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [40]:
# ndenumerate ->return index,value
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


# Initialization different types of Arrays

All in 0's matrix

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

All in 1's matrix

In [43]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [44]:
np.ones((5,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

All in any fixed numbers

In [45]:
#np.full(shape,number)
np.full((4,2),99)

array([[99, 99],
       [99, 99],
       [99, 99],
       [99, 99]])

All in any list

In [46]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [47]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [48]:
np.full(a.shape,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

random number generator (rng)

In [49]:
# if we use the seed the random number does not change
# rng=np.random.default_rng(seed=1)
rng=np.random.default_rng()
rng.integers(1,7,(2,5))

array([[6, 1, 3, 6, 2],
       [4, 6, 4, 4, 2]])

In [50]:
#shuffel the array
rng=np.random.default_rng()
arr=np.array([1,2,3,4,5])
rng.shuffle(arr)
print(arr)


[3 5 4 1 2]


In [51]:
#choice some element random in array
print(rng.choice(arr,)) # random one
rng.choice(arr,size=(2,3))

4


array([[4, 2, 5],
       [1, 3, 4]])

All in random decimal numbers matrix

In [52]:
# we can implement seed like this also
np.random.seed(seed=1)
np.random.rand(4,2)

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01]])

In [53]:

np.random.random_sample(a.shape)

array([[0.39676747, 0.53881673, 0.41919451, 0.6852195 , 0.20445225,
        0.87811744, 0.02738759],
       [0.67046751, 0.4173048 , 0.55868983, 0.14038694, 0.19810149,
        0.80074457, 0.96826158]])

All in random float from standard normal distribution ->average=0

In [54]:
np.random.randn(2,3)  # the average =0

array([[ 1.13376944, -1.09989127, -0.17242821],
       [-0.87785842,  0.04221375,  0.58281521]])

All in random integer numbers matrix

In [55]:
#randint(range,size=())
np.random.randint(9,size=(4,3))

array([[4, 8, 1],
       [4, 0, 3],
       [2, 0, 4],
       [2, 7, 7]], dtype=int32)

In [56]:
np.random.randint(-3,4,size=(3,5))

array([[-1, -2, -3,  3, -2],
       [ 0,  3,  2,  1,  0],
       [ 2, -2,  0,  3, -3]], dtype=int32)

The matrix in identity

In [57]:
# this all in square matrix 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

repeat the array

In [58]:
# in 1D matrix   
#repeat(array_name,no_of_times_repeat)
arr=np.array([1,2,3])
rep1=np.repeat(arr,3)
print(rep1)

[1 1 1 2 2 2 3 3 3]


In [59]:
arr=np.array([1,2,3,4])
rep1=np.tile(arr,3)
print(rep1)

[1 2 3 4 1 2 3 4 1 2 3 4]


In [60]:
#  in 2D matrix to repeat the output lik [[1,2,3],[1,2,3],[1,2,3]]
arr=np.array([[1,2,3]])
rep1=np.repeat(arr,3,axis=0)
print(rep1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


Try to build the pattern exercise

In [61]:
output=np.ones((5,5))
print(output)
print()
z=np.zeros((3,3))
print(z)
print()
z[1,1]=9
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


copy the arr 

In [62]:
# This is not copy the array it assign to array
a=np.array([1,2,45,65,6])
b=a
print(b)
b[0]=100
print(a)
print(b)

[ 1  2 45 65  6]
[100   2  45  65   6]
[100   2  45  65   6]


In [63]:
#the copy the array by copy()
a=np.array([1,2,4,5,6])
b=a.copy()
print(b)
b[0]=100
print(b)
print(a)

[1 2 4 5 6]
[100   2   4   5   6]
[1 2 4 5 6]


return non zero value as index

In [64]:
np.nonzero([1,2,0,5,2,0,7]) # index

(array([0, 1, 3, 4, 6]),)

# Mathematics

In [65]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


addition / subration /muiltiplication / divisios

In [66]:
#addition
a+2  # not change the original array
# a+=2 # change in original array
# a

array([3, 4, 5, 6, 7])

In [67]:

#subraction
a-2

array([-1,  0,  1,  2,  3])

In [68]:
#multiplication
a*2

array([ 2,  4,  6,  8, 10])

In [69]:
#division
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [70]:
#moduls
a%2

array([1, 0, 1, 0, 1])

operation two array

In [71]:
b=np.array([1,0,1,0,1])
print(b)

[1 0 1 0 1]


In [72]:
#adding
a+b

array([2, 2, 4, 4, 6])

sin of array

In [73]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [74]:
# sqrt function
np.sqrt([1,4,9,16])

array([1., 2., 3., 4.])

In [75]:
#exponential -> np.exp -> e^x -> x is any number
np.exp([1,2])

array([2.71828183, 7.3890561 ])

In [76]:
# dot product 
# it is used in 1D array 
# product of same index  -> return  sum of the product 
# like ((1*4)+(4*3)+(6*5))
s1=np.array([1,4,6])
s2=np.array([2,3,5])
np.dot(s1,s2)

np.int64(44)

https://numpy.org/doc/stable/reference/routines.math.html

# Linear Algebra

matrix multiplication

In [77]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

find determination

In [78]:
c=np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

matrix Transpose as A^T

In [79]:
#transpose the array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
at=np.transpose(a)
print(at)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


Swap the axis of the matrrix

In [80]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a.shape)
swap=np.swapaxes(a,0,1)
print(swap.shape)
print(swap)

(4, 3)
(3, 4)
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


https://numpy.org/doc/stable/reference/routines.linalg.html

# Statistics

In [81]:
stats=np.array([[1,2,7],[4,5,6]])
print(stats)

[[1 2 7]
 [4 5 6]]


min / max /sum operation

In [82]:
np.min(stats)

np.int64(1)

In [83]:
np.min(stats,axis=1)

array([1, 4])

In [84]:
np.max(stats)

np.int64(7)

In [85]:
np.max(stats,axis=1)

array([7, 6])

In [86]:
np.max(stats,axis=0)

array([4, 5, 7])

In [87]:
np.sum(stats)

np.int64(25)

In [88]:
np.sum(stats,axis=1)

array([10, 15])

In [89]:
np.argmax(stats,axis=1) # return index of maximum

array([2, 2])

In [90]:
np.argmin([3,4,2,5,7,6]) # return index of minimum

np.int64(2)

# Reorganizing Array

changing the shape of matrix

In [91]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=np.reshape(before,(4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Any Matrix Converting into 1D array

In [92]:
# ravel changes are made in main array
before=before.ravel()
before[0]=100
print(before)
print(after)

[100   2   3   4   5   6   7   8]
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [93]:
# flatten changes are not made in main array
before=after.flatten()
before[0]=200
print(before)
print(after) 

[200   2   3   4   5   6   7   8]
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


concatenate the array

In [94]:
a1=np.array([1,2,3,4])
a2=np.array([2,3])
np.concatenate((a1,a2,a1))

array([1, 2, 3, 4, 2, 3, 1, 2, 3, 4])

vertical stacking vector

In [95]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

Horizantal stack vector

In [96]:
np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

In [97]:
v1=np.array([[1,2],[3,4]])
v2=np.array([[5,6],[7,8]])
np.hstack([v1,v2,v2,v1])

array([[1, 2, 5, 6, 5, 6, 1, 2],
       [3, 4, 7, 8, 7, 8, 3, 4]])

split the Matrix equal part

In [98]:
v1=np.array([[1,2],[3,4],[5,6],[7,8]])
np.split(v1,2) # split into equal part else error

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [99]:
np.hsplit(v1,2)

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [100]:
np.vsplit(v1,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

broadcasting array

rules:
1. shape are equal,they are compatible
2. if one is 1,it can be streached to match yo other
3. if shapes are different and not 1 or equal ->Error

In [101]:
image=np.array([[200,180],[130,190]])
print(image.shape)
inc=np.array([50])
print(inc.shape)
inc=image+inc  # rule 2
print(inc)
print(inc.shape)


(2, 2)
(1,)
[[250 230]
 [180 240]]
(2, 2)


vectorization: 
    ->convert regular function to be applied on a array
1. slower than loop
2. look the code clean and readability

In [102]:
sample=np.array([1,2,3,4,5])
def square(x):
    return x*x
vfun=np.vectorize(square)
print(vfun(sample))

[ 1  4  9 16 25]


null and infinate

In [103]:
a=np.array([1,2,np.nan,np.inf,4,-np.inf,6])
print(a)
print(np.isnan(a))
print(np.isinf(a))
print(np.isneginf(a))

[  1.   2.  nan  inf   4. -inf   6.]
[False False  True False False False False]
[False False False  True False  True False]
[False False False False False  True False]


# Miscellaneous

read the data

In [104]:
file_data=np.genfromtxt('data.txt',delimiter=',')
print(file_data)
#converting folat into int
file_data=file_data.astype('int32')
print(file_data)

[[1. 2. 3. 7. 5. 6. 6. 9. 5.]
 [3. 2. 4. 6. 5. 7. 3. 6. 6.]
 [9. 8. 7. 5. 6. 7. 3. 6. 8.]]
[[1 2 3 7 5 6 6 9 5]
 [3 2 4 6 5 7 3 6 6]
 [9 8 7 5 6 7 3 6 8]]


Boolean Masking and Advanced indexing

In [105]:
file_data>5

array([[False, False, False,  True, False,  True,  True,  True, False],
       [False, False, False,  True, False,  True, False,  True,  True],
       [ True,  True,  True, False,  True,  True, False,  True,  True]])

In [106]:
file_data[file_data>5]

array([7, 6, 6, 9, 6, 7, 6, 6, 9, 8, 7, 6, 7, 6, 8], dtype=int32)

In [107]:
# checking by row
np.any(file_data>7,axis=1)

array([ True, False,  True])

In [108]:
# checking by column
np.any(file_data>7,axis=0)

array([ True,  True, False, False, False, False, False,  True,  True])

In [109]:
# all the value is greater 
np.all(file_data>4,axis=0)

array([False, False, False,  True,  True,  True, False,  True,  True])

In [110]:
# condition  and '&' -> and operator
((file_data>2) & (file_data<6))

array([[False, False,  True, False,  True, False, False, False,  True],
       [ True, False,  True, False,  True, False,  True, False, False],
       [False, False, False,  True, False, False,  True, False, False]])

# Aggregated Function

In [111]:
arr=np.array([1,2,3,4,5,6])
np.sum(arr)

np.int64(21)

In [112]:
# mean -> average
np.mean(arr)

np.float64(3.5)

In [113]:
#median -> medium or centeer value
np.median(arr)

np.float64(3.5)

In [114]:
#std
np.std(arr)

np.float64(1.707825127659933)

In [115]:
#var
np.var(arr)

np.float64(2.9166666666666665)

Cumalative operation

In [116]:
#cumalative sum 
print(arr)
np.cumsum(arr) # sum it by running

[1 2 3 4 5 6]


array([ 1,  3,  6, 10, 15, 21])

In [117]:
#cumalative product
np.cumprod(arr)

array([  1,   2,   6,  24, 120, 720])

condition based like if

In [118]:
print(arr)
np.where( arr%2==0 ,'even','odd')

[1 2 3 4 5 6]


array(['odd', 'even', 'odd', 'even', 'odd', 'even'], dtype='<U4')

In [119]:
# argwhere -> perform and return index
np.argwhere(arr%2==0) 

array([[1],
       [3],
       [5]])

In [120]:
#2D matrix
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
np.argwhere(a<5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0]])

logical operator

In [121]:
print(arr)
np.logical_and(arr>2,arr<5)

[1 2 3 4 5 6]


array([False, False,  True,  True, False, False])

In [122]:
ans=np.logical_or(arr<2,arr>5)
print(ans)
arr[ans]


[ True False False False False  True]


array([1, 6])

# save load read file

save the numpy file

In [123]:
arr=np.array([[1,2,3],[4,5,6]])
np.save("C:\\Users\\Mowneesh\\OneDrive\\Desktop\\pyhton\\sampledata",arr) # file as sampledata.npy
print("numpy array save successfully") 

numpy array save successfully


load the numpy file

In [124]:
arr=np.load("C:\\Users\\Mowneesh\\OneDrive\\Desktop\\pyhton\\sampledata.npy") 
print(arr)

[[1 2 3]
 [4 5 6]]


save multiple numpy file

In [125]:
arr1=np.array([[2,3,5,6,7,8],[1,2,3,5,4,5]])
arr2=np.array([1.1,2.2,3.3,4.4,5.5])
arr3=np.array([2007,2002,1986,1967])
np.savez("data",arr1,arr2,arr3)  # file as data.npz
print("Saved multiple file")  

Saved multiple file


load multiple file

In [126]:
arr=np.load("data.npz")
l1=arr["arr_0"]
l2=arr["arr_1"]
l3=arr["arr_2"]

print(l1)
print(l2)
print(l3)

[[2 3 5 6 7 8]
 [1 2 3 5 4 5]]
[1.1 2.2 3.3 4.4 5.5]
[2007 2002 1986 1967]


Read the data

In [127]:
read=np.genfromtxt("data.txt",delimiter=',')
print(read)

[[1. 2. 3. 7. 5. 6. 6. 9. 5.]
 [3. 2. 4. 6. 5. 7. 3. 6. 6.]
 [9. 8. 7. 5. 6. 7. 3. 6. 8.]]
